lapTime = str(4323)
totalTime = str(434)
strlap = str(1)
print('Lap #', end = '')
l = len(strlap)
print(strlap.rjust(3-l)+':', end='')
l = len(totalTime)
print(totalTime.rjust(8-l), end='')
print('('.rjust(3), end ='')
l = len(lapTime)
print(lapTime.rjust(15-l), end='')
print(')')